// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.5
// source: uav.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FromDrone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatteryVoltage float32 `protobuf:"fixed32,1,opt,name=batteryVoltage,proto3" json:"batteryVoltage,omitempty"`
	CurrentDraw    float32 `protobuf:"fixed32,2,opt,name=currentDraw,proto3" json:"currentDraw,omitempty"`
	Altitude       float32 `protobuf:"fixed32,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Latitude       float32 `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float32 `protobuf:"fixed32,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Temperature    float32 `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MotorRPM       float32 `protobuf:"fixed32,7,opt,name=motorRPM,proto3" json:"motorRPM,omitempty"`
	Gyro           float32 `protobuf:"fixed32,8,opt,name=gyro,proto3" json:"gyro,omitempty"`
	Accel          float32 `protobuf:"fixed32,9,opt,name=accel,proto3" json:"accel,omitempty"`
}

func (x *FromDrone) Reset() {
	*x = FromDrone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uav_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromDrone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromDrone) ProtoMessage() {}

func (x *FromDrone) ProtoReflect() protoreflect.Message {
	mi := &file_uav_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromDrone.ProtoReflect.Descriptor instead.
func (*FromDrone) Descriptor() ([]byte, []int) {
	return file_uav_proto_rawDescGZIP(), []int{0}
}

func (x *FromDrone) GetBatteryVoltage() float32 {
	if x != nil {
		return x.BatteryVoltage
	}
	return 0
}

func (x *FromDrone) GetCurrentDraw() float32 {
	if x != nil {
		return x.CurrentDraw
	}
	return 0
}

func (x *FromDrone) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *FromDrone) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *FromDrone) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *FromDrone) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *FromDrone) GetMotorRPM() float32 {
	if x != nil {
		return x.MotorRPM
	}
	return 0
}

func (x *FromDrone) GetGyro() float32 {
	if x != nil {
		return x.Gyro
	}
	return 0
}

func (x *FromDrone) GetAccel() float32 {
	if x != nil {
		return x.Accel
	}
	return 0
}

type ToDrone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Throttle   int32 `protobuf:"varint,1,opt,name=throttle,proto3" json:"throttle,omitempty"`
	Rudder     int32 `protobuf:"varint,2,opt,name=rudder,proto3" json:"rudder,omitempty"`
	Aileron    int32 `protobuf:"varint,3,opt,name=aileron,proto3" json:"aileron,omitempty"`
	Elevator   int32 `protobuf:"varint,4,opt,name=elevator,proto3" json:"elevator,omitempty"`
	MotorPower int32 `protobuf:"varint,5,opt,name=motorPower,proto3" json:"motorPower,omitempty"`
	Aux1       int32 `protobuf:"varint,6,opt,name=aux1,proto3" json:"aux1,omitempty"`
	Aux2       int32 `protobuf:"varint,7,opt,name=aux2,proto3" json:"aux2,omitempty"`
	Aux3       int32 `protobuf:"varint,8,opt,name=aux3,proto3" json:"aux3,omitempty"`
}

func (x *ToDrone) Reset() {
	*x = ToDrone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uav_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToDrone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDrone) ProtoMessage() {}

func (x *ToDrone) ProtoReflect() protoreflect.Message {
	mi := &file_uav_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDrone.ProtoReflect.Descriptor instead.
func (*ToDrone) Descriptor() ([]byte, []int) {
	return file_uav_proto_rawDescGZIP(), []int{1}
}

func (x *ToDrone) GetThrottle() int32 {
	if x != nil {
		return x.Throttle
	}
	return 0
}

func (x *ToDrone) GetRudder() int32 {
	if x != nil {
		return x.Rudder
	}
	return 0
}

func (x *ToDrone) GetAileron() int32 {
	if x != nil {
		return x.Aileron
	}
	return 0
}

func (x *ToDrone) GetElevator() int32 {
	if x != nil {
		return x.Elevator
	}
	return 0
}

func (x *ToDrone) GetMotorPower() int32 {
	if x != nil {
		return x.MotorPower
	}
	return 0
}

func (x *ToDrone) GetAux1() int32 {
	if x != nil {
		return x.Aux1
	}
	return 0
}

func (x *ToDrone) GetAux2() int32 {
	if x != nil {
		return x.Aux2
	}
	return 0
}

func (x *ToDrone) GetAux3() int32 {
	if x != nil {
		return x.Aux3
	}
	return 0
}

type Acknowledged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *Acknowledged) Reset() {
	*x = Acknowledged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uav_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Acknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledged) ProtoMessage() {}

func (x *Acknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_uav_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledged.ProtoReflect.Descriptor instead.
func (*Acknowledged) Descriptor() ([]byte, []int) {
	return file_uav_proto_rawDescGZIP(), []int{2}
}

func (x *Acknowledged) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

type UploadImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B []byte `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *UploadImage) Reset() {
	*x = UploadImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uav_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImage) ProtoMessage() {}

func (x *UploadImage) ProtoReflect() protoreflect.Message {
	mi := &file_uav_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImage.ProtoReflect.Descriptor instead.
func (*UploadImage) Descriptor() ([]byte, []int) {
	return file_uav_proto_rawDescGZIP(), []int{3}
}

func (x *UploadImage) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

var File_uav_proto protoreflect.FileDescriptor

var file_uav_proto_rawDesc = []byte{
	0x0a, 0x09, 0x75, 0x61, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x93, 0x02, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d,
	0x44, 0x72, 0x6f, 0x6e, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x62,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x61, 0x77, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x74, 0x6f, 0x72,
	0x52, 0x50, 0x4d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6d, 0x6f, 0x74, 0x6f, 0x72,
	0x52, 0x50, 0x4d, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x79, 0x72, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x67, 0x79, 0x72, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x63, 0x65, 0x6c,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x63, 0x63, 0x65, 0x6c, 0x22, 0xcf, 0x01,
	0x0a, 0x07, 0x74, 0x6f, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x72,
	0x6f, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x68, 0x72,
	0x6f, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x75, 0x64, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x75, 0x64, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x61, 0x69, 0x6c, 0x65, 0x72, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x76, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x76, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x50, 0x6f, 0x77, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x50, 0x6f,
	0x77, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x78, 0x31, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x61, 0x75, 0x78, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x78, 0x32, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x75, 0x78, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x75, 0x78, 0x33, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x75, 0x78, 0x33, 0x22,
	0x1c, 0x0a, 0x0c, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x12,
	0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x61, 0x22, 0x1b, 0x0a,
	0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x62, 0x32, 0x4b, 0x0a, 0x0a, 0x75, 0x61,
	0x76, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x3d, 0x0a, 0x09, 0x62, 0x69, 0x44, 0x69,
	0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2e, 0x74, 0x6f, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x72, 0x6f, 0x6e,
	0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uav_proto_rawDescOnce sync.Once
	file_uav_proto_rawDescData = file_uav_proto_rawDesc
)

func file_uav_proto_rawDescGZIP() []byte {
	file_uav_proto_rawDescOnce.Do(func() {
		file_uav_proto_rawDescData = protoimpl.X.CompressGZIP(file_uav_proto_rawDescData)
	})
	return file_uav_proto_rawDescData
}

var file_uav_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_uav_proto_goTypes = []interface{}{
	(*FromDrone)(nil),    // 0: protofiles.fromDrone
	(*ToDrone)(nil),      // 1: protofiles.toDrone
	(*Acknowledged)(nil), // 2: protofiles.acknowledged
	(*UploadImage)(nil),  // 3: protofiles.uploadImage
}
var file_uav_proto_depIdxs = []int32{
	1, // 0: protofiles.uavControl.biDirComm:input_type -> protofiles.toDrone
	0, // 1: protofiles.uavControl.biDirComm:output_type -> protofiles.fromDrone
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uav_proto_init() }
func file_uav_proto_init() {
	if File_uav_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uav_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromDrone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uav_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToDrone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uav_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Acknowledged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uav_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uav_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uav_proto_goTypes,
		DependencyIndexes: file_uav_proto_depIdxs,
		MessageInfos:      file_uav_proto_msgTypes,
	}.Build()
	File_uav_proto = out.File
	file_uav_proto_rawDesc = nil
	file_uav_proto_goTypes = nil
	file_uav_proto_depIdxs = nil
}
